spring:
  datasource:
    name: test-mybatisplus
    url: jdbc:mysql://localhost:3306/test_mybatisplus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.dongxibao.server: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      logic-delete-field: del_flag  #全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: id_worker
      capital-mode: true
server:
  port: 8081
