package com.dongxibao.client.webservice;

import com.dongxibao.client.common.GlobalInterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-05-30T17:00:12.892+08:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "TestServerService",
                  wsdlLocation = GlobalInterface.INSERT_USER,
                  targetNamespace = "http://insertuser.server.dongxibao.com/")
public class TestServerService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://insertuser.server.dongxibao.com/", "TestServerService");
    public final static QName TestServerServiceImplPort = new QName("http://insertuser.server.dongxibao.com/", "TestServerServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL(GlobalInterface.INSERT_USER);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestServerService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", GlobalInterface.INSERT_USER);
        }
        WSDL_LOCATION = url;
    }

    public TestServerService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestServerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServerService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestServerService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestServerService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestServerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestServerService
     */
    @WebEndpoint(name = "TestServerServiceImplPort")
    public TestServerService getTestServerServiceImplPort() {
        return super.getPort(TestServerServiceImplPort, TestServerService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestServerService
     */
    @WebEndpoint(name = "TestServerServiceImplPort")
    public TestServerService getTestServerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TestServerServiceImplPort, TestServerService.class, features);
    }

}
