package com.dongxibao.client.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-05-30T17:00:12.864+08:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://insertuser.server.dongxibao.com/", name = "TestServerService")
@XmlSeeAlso({ObjectFactory.class})
public interface TestServerService {

    @WebMethod(action = "http://insertuser.server.dongxibao.com/user")
    @RequestWrapper(localName = "insertUser", targetNamespace = "http://insertuser.server.dongxibao.com/", className = "com.dongxibao.client.webservice.InsertUser")
    @ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://insertuser.server.dongxibao.com/", className = "com.dongxibao.client.webservice.InsertUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public RestResult insertUser(

            @WebParam(name = "userDTO", targetNamespace = "http://insertuser.server.dongxibao.com/")
                    com.dongxibao.client.webservice.UserDTO userDTO
    );
}
